AutoBlackLevel: true
AutoExposure: true
AutoGain: true
Binning: 1
BlackLevelOffset: 0.5
DisparityMapAOI: false
Exposure: 0.9159
FlexView: 4
FrontLight: false
Gain: 1.0
GainBoost: false
HardwareGamma: true
Hdr: false
PixelClock: 40
Projector: true
TargetBrightness: 40
TriggerMode: 0       #Software: 0, FallingEdge: 1, RisingEdge: 2
MinimumDisparity: -133
NumberOfDisparities: 256
OptimizationProfile: 2
Scaling: 1.0
DepthChangeCost: 5
DepthStepCost: 30
ShadowingThreshold: 1
UniquenessRatio: 10
MedianFilterRadius: 1
SpeckleComponentThreshold: 3
SpeckleRegionSize: 150
FillBorderSpread: 3
FillRegionSize: 150
